const SOURCE_SEARCHES = [
  ['Facebook Marketplace', 'https://www.facebook.com/marketplace/brisbane/search/?query={q}', true],
  ['Gumtree Brisbane', 'https://www.gumtree.com.au/s-brisbane/{q}/k0l3005721', false],
  ['eBay AU', 'https://www.ebay.com.au/sch/i.html?_nkw={q}&_sop=10', false],
  ['OzBargain', 'https://www.ozbargain.com.au/search/node/{q}', false],
  ['Reddit Australia', 'https://www.reddit.com/search/?q={q}%20Australia%20OR%20Brisbane&sort=new', false],
  ['Grays Auctions', 'https://www.grays.com/search?q={q}', false],
  ['Pickles Auctions', 'https://www.pickles.com.au/search?q={q}', false],
  ['AllBids', 'https://www.allbids.com.au/search?search={q}', false],
  ['Lloyds Auctions', 'https://www.lloydsauctions.com.au/search?Search={q}', false],
  ['Cash Converters', 'https://www.cashconverters.com.au/search-results?query={q}', false],
  ['CeX Australia', 'https://au.webuy.com/search?stext={q}', false],
  ['Reebelo', 'https://reebelo.com.au/search?q={q}', false],
  ['Umart', 'https://www.umart.com.au/search.php?keywords={q}', false],
  ['Computer Alliance', 'https://www.computeralliance.com.au/search?search={q}', false],
  ['Scorptec', 'https://www.scorptec.com.au/search?keyword={q}', false],
  ['Mwave', 'https://www.mwave.com.au/searchresult?w={q}', false],
  ['PC Case Gear', 'https://www.pccasegear.com/search?query={q}', false],
  ['Centre Com', 'https://www.centrecom.com.au/catalogsearch/result/?q={q}', false],
  ['Amazon AU', 'https://www.amazon.com.au/s?k={q}', false],
  ['Kogan', 'https://www.kogan.com/au/shop/?q={q}', false],
  ['Catch', 'https://www.catch.com.au/search?query={q}', false],
  ['StaticICE', 'https://www.staticice.com.au/cgi-bin/search.cgi?q={q}', false]
];

const QUERIES = ['RTX 4090', 'RTX 4080', 'RTX 3090', 'RX 7900 XTX', 'Ryzen 9 7950X3D', 'Ryzen 7 7800X3D', 'i9 14900K', 'i9 13900K', 'X670E motherboard', 'Z790 motherboard', 'DDR5 64GB', 'DDR5 128GB', '1000W platinum PSU', '1200W PSU', 'gaming PC RTX 4090', 'gaming PC RTX 4080'];
const HIGH = ['4090','4080','4070 ti','3090','3080 ti','7900 xtx','7900xtx','7950x3d','7950x','7800x3d','14900k','13900k','x670e','z790','ddr5','64gb','128gb','1000w','1200w','platinum','rog','strix','aorus','threadripper'];
const JUNK = ['gt 1030','gtx 750','gtx 760','gtx 960','ddr3','office pc','sff','faulty','not working','for parts only','broken'];
const EST = [['4090',2600],['4080',1500],['3090',1100],['7900 xtx',1300],['7950x3d',850],['7800x3d',600],['14900k',850],['13900k',650],['x670e',600],['z790',500],['64gb',260],['128gb',520],['1000w',280],['1200w',360],['gaming pc',1800]];

exports.config = { schedule: '0 22,10 * * *' };

function j(statusCode, body) { return { statusCode, headers: { 'content-type': 'application/json', 'access-control-allow-origin': '*', 'cache-control': 'public, max-age=900' }, body: JSON.stringify(body) }; }
function c(v='') { return String(v).replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim(); }
function enc(v) { return encodeURIComponent(v); }
async function txt(url) { const ac = new AbortController(); const t = setTimeout(() => ac.abort(), 9000); try { const r = await fetch(url, { signal: ac.signal, headers: { 'user-agent':'PCScavenger/0.3', accept:'application/rss+xml,application/json,text/xml,text/html' }}); if (!r.ok) throw new Error(`${r.status} ${r.statusText}`); return await r.text(); } finally { clearTimeout(t); } }
function val(title) { const l = title.toLowerCase(); const hit = EST.find(([k]) => l.includes(k)); return hit ? hit[1] : 300; }
function price(title) { const l = title.toLowerCase(); if (/\bfree\b|giveaway|give away/.test(l)) return 0; const m = title.match(/\$\s?([0-9][0-9,]*)/); return m ? Number(m[1].replace(/,/g,'')) : null; }
function cat(t) { const l=t.toLowerCase(); if(/rtx|radeon|gpu|graphics|geforce|7900 xtx/.test(l)) return 'GPU'; if(/ryzen|i9|i7|7950|7800x3d|14900|13900|cpu/.test(l)) return 'CPU'; if(/motherboard|x670|z790|z690|b650|am5/.test(l)) return 'Motherboard'; if(/psu|power supply|1000w|1200w|platinum/.test(l)) return 'PSU'; if(/ddr5|ram|memory|64gb|128gb/.test(l)) return 'RAM'; if(/gaming pc|workstation|desktop|computer/.test(l)) return 'Complete PC'; return 'Peripheral'; }
function dist(t,s) { const l=`${t} ${s}`.toLowerCase(); if(l.includes('calamvale')) return 0; if(l.includes('sunnybank')) return 5; if(l.includes('brisbane')) return 18; if(l.includes('logan')) return 20; if(l.includes('gold coast')) return 75; if(l.includes('sunshine coast')) return 100; if(l.includes('qld')||l.includes('queensland')) return 35; return 999; }
function tier(p,v,t) { const l=t.toLowerCase(); if(p===0||/\bfree\b|giveaway/.test(l)) return 'Ultimate Prize'; if(p===null) return 'Unknown Price'; const r=v/Math.max(p,1); if(r>=4||p<=150) return 'Disgustingly Cheap'; if(r>=2.2) return 'Cheap'; if(r>=1.4) return 'Discounted'; if(r>=1.15) return 'Showroom Slashed'; return 'On Sale'; }
function score(o) { const l=`${o.title} ${o.notes}`.toLowerCase(); const hi=HIGH.filter(x=>l.includes(x)).length; const bad=JUNK.filter(x=>l.includes(x)).length; const gap=o.price==null?0:Math.max(o.valueEstimate-o.price,0); const ratio=o.price===0?50:(o.price?o.valueEstimate/o.price:1); const tb={ 'Ultimate Prize':1500,'Disgustingly Cheap':900,Cheap:550,Discounted:260,'Showroom Slashed':140,'On Sale':60,'Unknown Price':35 }[o.tier]||0; const cb={GPU:300,CPU:240,Motherboard:210,PSU:180,RAM:150,'Complete PC':140,Peripheral:20}[o.category]||0; return Math.round(tb+cb+hi*90+gap/4+ratio*25-bad*500-(o.distanceKm>150?70:o.distanceKm/2)); }
function deal({title,link,source,listedAt,seller='Unknown seller',contact='Open listing',notes=''}) { title=c(title); const p=price(title); const v=val(title); const o={ id:`${source}-${title}-${link}`.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,120), title, category:cat(title), tier:tier(p,v,title), price:p, valueEstimate:v, source, location:dist(title,source)===999?'Australia / freight or unknown':'Brisbane / SE QLD signal', distanceKm:dist(title,source), listedAt:listedAt||new Date().toISOString(), specs:HIGH.filter(x=>title.toLowerCase().includes(x)).slice(0,4), seller, contact, link, image:`https://placehold.co/480x320/111827/f8fafc?text=${enc(cat(title))}`, notes:c(notes).slice(0,260)||'Verify condition, serials, warranty, proof of function and seller legitimacy before paying.' }; return { ...o, score:score(o) }; }
function keep(o) { const l=`${o.title} ${o.notes}`.toLowerCase(); return HIGH.some(x=>l.includes(x)) && !JUNK.some(x=>l.includes(x)); }
function rss(xml, source) { return [...xml.matchAll(/<item[\s\S]*?<\/item>/gi)].slice(0,20).map(m => { const raw=m[0]; const title=raw.match(/<title><!\[CDATA\[([\s\S]*?)\]\]><\/title>|<title>([\s\S]*?)<\/title>/i)?.[1]||raw.match(/<title><!\[CDATA\[([\s\S]*?)\]\]><\/title>|<title>([\s\S]*?)<\/title>/i)?.[2]||'Untitled'; const link=raw.match(/<link>([\s\S]*?)<\/link>/i)?.[1]||'#'; const pd=raw.match(/<pubDate>([\s\S]*?)<\/pubDate>/i)?.[1]; const desc=raw.match(/<description><!\[CDATA\[([\s\S]*?)\]\]><\/description>|<description>([\s\S]*?)<\/description>/i)?.[1]||''; return deal({title,link,source,listedAt:pd?new Date(pd).toISOString():new Date().toISOString(),notes:desc}); }); }
async function google() { const key=process.env.GOOGLE_CSE_API_KEY, cx=process.env.GOOGLE_CSE_ID; if(!key||!cx) return []; const out=[]; const qs=SOURCE_SEARCHES.flatMap(([name,,login])=>QUERIES.slice(0,8).map(q=>`site:${domainFor(name)} ${q} Brisbane OR Queensland OR Australia ${login?'marketplace':''}`)).concat(['Brisbane free RTX 4090 giveaway','Brisbane cheap RTX 4080','Gold Coast RTX 4090 Gumtree','Australia used 7950X3D']); for (const q of qs.slice(0,50)) { try { const data=JSON.parse(await txt(`https://www.googleapis.com/customsearch/v1?key=${enc(key)}&cx=${enc(cx)}&q=${enc(q)}&num=5&dateRestrict=m1`)); for (const it of data.items||[]) out.push(deal({title:it.title,link:it.link,source:`Google CSE: ${it.displayLink||q.slice(0,40)}`,seller:it.displayLink||'Search result',contact:'Open listing / login at source if required',notes:it.snippet||''})); } catch(e) {} } return out; }
function domainFor(n){ const map={ 'Facebook Marketplace':'facebook.com/marketplace','Gumtree Brisbane':'gumtree.com.au','eBay AU':'ebay.com.au','OzBargain':'ozbargain.com.au','Reddit Australia':'reddit.com','Grays Auctions':'grays.com','Pickles Auctions':'pickles.com.au','AllBids':'allbids.com.au','Lloyds Auctions':'lloydsauctions.com.au','Cash Converters':'cashconverters.com.au','CeX Australia':'au.webuy.com','Reebelo':'reebelo.com.au','Umart':'umart.com.au','Computer Alliance':'computeralliance.com.au','Scorptec':'scorptec.com.au','Mwave':'mwave.com.au','PC Case Gear':'pccasegear.com','Centre Com':'centrecom.com.au','Amazon AU':'amazon.com.au','Kogan':'kogan.com','Catch':'catch.com.au','StaticICE':'staticice.com.au'}; return map[n]||'google.com'; }
async function reddit(){ const q=enc('(rtx OR ryzen OR 4090 OR 4080 OR 3090 OR 7900xtx OR 7950x3d OR x670e OR z790 OR ddr5) (brisbane OR qld OR australia OR au)'); const d=JSON.parse(await txt(`https://www.reddit.com/search.json?q=${q}&sort=new&t=week&limit=50`)); return (d?.data?.children||[]).map(x=>x.data).filter(x=>x?.title).map(p=>deal({title:p.title,link:`https://www.reddit.com${p.permalink}`,source:`Reddit / ${p.subreddit_name_prefixed}`,listedAt:new Date((p.created_utc||Date.now()/1000)*1000).toISOString(),seller:p.author||'Reddit user',contact:'Reddit comment or DM',notes:p.selftext||''})); }
async function ebay(){ const out=[]; for(const q of QUERIES.slice(0,10)){ try{ out.push(...rss(await txt(`https://www.ebay.com.au/sch/i.html?_nkw=${enc(q)}&_sop=10&_rss=1`),`eBay AU: ${q}`)); }catch(e){} } return out; }
async function ozb(){ const out=[]; for(const q of QUERIES.slice(0,10)){ try{ out.push(...rss(await txt(`https://www.ozbargain.com.au/search/rss.xml?q=${enc(q)}`),`OzBargain: ${q}`)); }catch(e){} } return out; }
function fallback(){ return SOURCE_SEARCHES.flatMap(([name,url,login])=>QUERIES.slice(0,3).map(q=>deal({title:`${q} - ${name} manual hunt`,link:url.replace('{q}',enc(q)),source:name,seller:name,contact:login?'Log in at source, then return here':'Open source search',notes:login?'Login-required marketplace. App preserves your Interested/Pass state while you open this source.':'Manual source search fallback while live API/feed is unavailable.'}))); }
function dedupe(a){ const s=new Set(); return a.filter(x=>{const k=`${x.title}|${x.link}`.toLowerCase(); if(s.has(k)) return false; s.add(k); return true;}); }
exports.handler = async () => { const errors=[]; const items=[]; for(const [name,fn] of [['Google CSE',google],['Reddit',reddit],['eBay',ebay],['OzBargain',ozb]]){ try{ items.push(...await fn()); }catch(e){ errors.push(`${name}: ${e.message}`); } } const pool=items.length?items:fallback(); const deals=dedupe(pool).filter(x=>keep(x)||['Ultimate Prize','Disgustingly Cheap','Unknown Price'].includes(x.tier)).sort((a,b)=>b.score-a.score).slice(0,80); return j(200,{ scannedAt:new Date().toISOString(), googleCseEnabled:Boolean(process.env.GOOGLE_CSE_API_KEY&&process.env.GOOGLE_CSE_ID), resultCount:deals.length, errors, sourceSearches:SOURCE_SEARCHES.map(([name,url,loginRequired])=>({name,url:url.replace('{q}',enc('RTX 4090')),loginRequired})), deals }); };
